version: '3.1'

services:
  db:
    image: bitnami/postgresql:16
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgresql:/bitnami/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRESQL_USERNAME=sustc
      - POSTGRESQL_PASSWORD=sustc
      - POSTGRESQL_INITDB_ARGS=--lc-collate=C --encoding=UTF8